### ISSUE TITLE
what automation is a available for getting the output XLSX files to the user facilities?

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/metadata-template-transformation#34]

**Comment by mslarae13** [comment]
No automation needed. it's a triggered transformation. Eventually, we'll have a review interface and an API that will use this code. 
No goals to ever make the template transformation automated. 
Closing as not planned.

**Comment by turbomam** [comment]
What are the differences between "automation" and "triggered transformation"? Is the point here that under some circumstances (like the submission of a Submission Portal interface), a person will run the code, get a spreadsheet, and then email it to a user facility contact?

I'm sharing my opinion that manual launch of the code and manual emailing of a spreadsheet should be avoided. If "triggered transformation" means that one or both of those manual steps aren't necessary, then I don't have any further opinions. :-)

**Comment by mslarae13** [comment]
Both those manual steps are currently happening. I run the etl scrip. Get an excel file. Email it to JGI PM.
As a renewal task, we'll propose the reviewer interface, and the submission portal will have a "send to user facility button" that will use an API to share the data.

The ETL will still be used to send the data to an API, to share to JGI/EMSL. & spreadsheets will no longer be generated. But that's all future work.

**Comment by mslarae13** [comment]
SO basically, I don't want automated xlsx files. I want automated API shared data. And that's a future goal.
